### ISSUE TITLE
Does not build on OSX.

### ISSUE THREAD

**Issue by omenking** [schmooblidon/meleelight#115]
I believe the Electron version needs to be updated.

```
error /Users/andrew/Desktop/meleelight/node_modules/electron: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /Users/andrew/Desktop/meleelight/node_modules/electron
Output:
/Users/andrew/Desktop/meleelight/node_modules/electron/install.js:48
  throw err
  ^

Error: Failed to find Electron v1.8.0 for darwin-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-darwin-x64.zip
    at Request.<anonymous> (/Users/andrew/Desktop/meleelight/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
```

**Comment by dscdac** [comment]
Hi,
It failed to me using node v10.4.1.

Try downgrading to a node v6.x.x and running `node audit fix --force` if necessary.
In my case it modified 3 packages:
<img width="403" alt="screen shot 2018-06-29 at 11 39 42" src="https://user-images.githubusercontent.com/6484161/42088389-39050516-7b91-11e8-8509-1e91a02b5788.png">
